AllCops:
  Exclude:
    - bin/*
    - tmp/**
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/**
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 500

Layout/LineLength:
  Max: 154

Metrics/ParameterLists:
  Exclude:
    - 'app/concepts/**/operations/**'

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  EnforcedStyle: braces

Style/MultilineBlockChain:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: aligned

Style/ParallelAssignment:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
