version: '3.1'

networks:
  net:

services:
  db:
    image: postgres:alpine
     ports:
      - 5432:5432
    env_file:
      - .env
   networks:
      net:
        aliases:
          - db
    volumes:
      - my_db_data:/var/lib/postgresql/data

  web:
    image: my_app
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - web

volumes:
  my_db_data:
